### ISSUE TITLE
Any idea why?

### ISSUE THREAD

**Issue by CebbyS** [natanfudge/artifice#28]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 19.02.21 10:22
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "net.minecraft.util.Identifier.toString()" because "this.identifier" is null
	at com.swordglowsblue.artifice.impl.ArtificeResourcePackImpl.toClientResourcePackProfile(ArtificeResourcePackImpl.java:440)
	at com.swordglowsblue.artifice.impl.ArtificeAssetsResourcePackProvider.register(ArtificeAssetsResourcePackProvider.java:20)
	at net.minecraft.resource.ResourcePackManager.providePackProfiles(ResourcePackManager.java:50)
	at net.minecraft.resource.ResourcePackManager.scanPacks(ResourcePackManager.java:38)
	at net.minecraft.client.MinecraftClient.redirect$zgc000$enableNonOptional(MinecraftClient.java:4705)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:454)
	at net.minecraft.client.main.Main.main(Main.java:149)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.swordglowsblue.artifice.impl.ArtificeResourcePackImpl.toClientResourcePackProfile(ArtificeResourcePackImpl.java:440)
	at com.swordglowsblue.artifice.impl.ArtificeAssetsResourcePackProvider.register(ArtificeAssetsResourcePackProvider.java:20)
	at net.minecraft.resource.ResourcePackManager.providePackProfiles(ResourcePackManager.java:50)
	at net.minecraft.resource.ResourcePackManager.scanPacks(ResourcePackManager.java:38)
	at net.minecraft.client.MinecraftClient.redirect$zgc000$enableNonOptional(MinecraftClient.java:4705)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:454)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 14.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1110028800 bytes (1058 MB) / 2111832064 bytes (2014 MB) up to 2111832064 bytes (2014 MB)
	CPUs: 12
	JVM Flags: 1 total; -XX:+ShowCodeDetailsInExceptionMessages
	Fabric Mods: 
		artifice: Artifice 0.14.4+1.16.3
		atbyw: All The Blocks You Want (ATBYW) 1.3.4
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		blockus: Blockus 2.0.0+1.16.4
		byg: BYG 1.1.3
		celib: Celib - CebbyS Library Mod ${mod_version}
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.2
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		extrapieces: Extra Pieces 2.9.0
		fabric: Fabric API 0.28.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		jankson: Jankson 2.1.0+j1.2.0
		minecraft: Minecraft 1.16.4
		modmenu: Mod Menu 1.14.6+build.31
		slabref: Refabricated Slabs ${mod_version}
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
	Launched Version: Fabric
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.41, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

**Comment by natanfudge** [comment]
Please use the latest 1.16.5 version of artifice and try again.

**Comment by natanfudge** [comment]
No response

**Comment by CebbyS** [comment]
Sorry, I had a lot things to do. When I will check if the issue is fixed. Going to replay on this
